Traceback (most recent call last):
  File "/home/s1949624/RL_matching/main_network.py", line 219, in <module>
    train_dataset, val_dataset, targets = get_data()
  File "/home/s1949624/RL_matching/main_network.py", line 151, in get_data
    train_indices, test_indices, _, _ = train_test_split(
  File "/local/s1949624/conda_envs/sanquin2/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2559, in train_test_split
    arrays = indexable(*arrays)
  File "/local/s1949624/conda_envs/sanquin2/lib/python3.10/site-packages/sklearn/utils/validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "/local/s1949624/conda_envs/sanquin2/lib/python3.10/site-packages/sklearn/utils/validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [2, 857418]
